name: Publish API

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions: { }

jobs:
  publish-api-docker-image:
    name: Publish API docker image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build, tag & push docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        id: docker
        with:
          docker-image: ghcr.io/govlt/national-boundaries-api
          docker-context: api
          file: api/Dockerfile
          environment: ${{ startsWith(github.ref, 'refs/tags/') && 'stable' ||  'preview' }}
          no-cache: true
          push: true
          cache-from: ''
          cache-to: ''